@echo Building pci_compat.h...
@java -jar idsparser.jar -input pci.ids -output pci_compat.h -template input_compat.tpl -compat
@echo.
@echo Building pci.h...
@java -jar idsparser.jar -input pci.ids -output pci.h -template input.tpl